"""Initial migration with fixed PK

Revision ID: 1fed805be004
Revises: 4867e795fd3f
Create Date: 2025-05-28 23:16:47.512718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fed805be004'
down_revision = '4867e795fd3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_config_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_config_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allowed_ips', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['network_config_id'], ['network_config.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_config_user_network_config_id'), 'network_config_user', ['network_config_id'], unique=False)
    op.create_index(op.f('ix_network_config_user_user_id'), 'network_config_user', ['user_id'], unique=False)
    
        # تغيير اسم العمود في network_config وإضافة قيد التفرد
    op.add_column('network_config', sa.Column('network_name', sa.String(length=100), nullable=True))
    op.drop_column('network_config', 'NETWORK_NAME')
    op.create_unique_constraint('uq_network_config_network_name', 'network_config', ['network_name'])
    
    # إضافة العمود في room وإنشاء المفتاح الخارجي
    op.add_column('room', sa.Column('network_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_room_network_name'), 'room', ['network_name'], unique=False)
    op.create_foreign_key(None, 'room', 'network_config', ['network_name'], ['network_name'], ondelete='CASCADE')
    
    # حذف الأعمدة غير المستخدمة
    op.drop_column('room', 'port')
    op.drop_column('room', 'vpn_password')
    op.drop_column('room', 'vpn_username')
    op.drop_column('room', 'vpn_hub')
    op.drop_column('room', 'server_ip')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('server_ip', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('vpn_hub', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('vpn_username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('vpn_password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_index(op.f('ix_room_network_name'), table_name='room')
    op.drop_column('room', 'network_name')
    op.add_column('network_config', sa.Column('NETWORK_NAME', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('network_config', 'network_name')
    op.drop_index(op.f('ix_network_config_user_user_id'), table_name='network_config_user')
    op.drop_index(op.f('ix_network_config_user_network_config_id'), table_name='network_config_user')
    op.drop_table('network_config_user')
    # ### end Alembic commands ### 