"""increase_wireguard_key_lengths

Revision ID: 33a320302769
Revises: 499fe5e465fc
Create Date: 2025-05-29 01:45:43.703082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a320302769'
down_revision = '499fe5e465fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network_config', 'private_key',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=44),
               existing_nullable=True)
    op.alter_column('network_config', 'public_key',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.String(length=44),
               existing_nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('user', 'verification_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user', 'private_key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=44),
               existing_nullable=True)
    op.alter_column('user', 'public_key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=44),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'public_key',
               existing_type=sa.String(length=44),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('user', 'private_key',
               existing_type=sa.String(length=44),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('user', 'verification_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('network_config', 'public_key',
               existing_type=sa.String(length=44),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)
    op.alter_column('network_config', 'private_key',
               existing_type=sa.String(length=44),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    # ### end Alembic commands ### 