"""Initial migration with fixed PK

Revision ID: 4867e795fd3f
Revises: 
Create Date: 2025-05-28 19:03:40.877592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4867e795fd3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('private_key', sa.String(length=15), nullable=True),
    sa.Column('public_key', sa.String(length=17), nullable=True),
    sa.Column('server_ip', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('NETWORK_NAME', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='unique_friendship')
    )
    op.create_index(op.f('ix_friendship_friend_id'), 'friendship', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friendship_user_id'), 'friendship', ['user_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_id'), 'chat_message', ['id'], unique=False)
    op.create_index(op.f('ix_chat_message_room_id'), 'chat_message', ['room_id'], unique=False)
    op.create_index(op.f('ix_chat_message_username'), 'chat_message', ['username'], unique=False)
    op.create_table('room_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('player_username', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_username'], ['user.username'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'player_username', name='unique_player_in_room')
    )
    op.create_index(op.f('ix_room_player_player_username'), 'room_player', ['player_username'], unique=False)
    op.create_index(op.f('ix_room_player_room_id'), 'room_player', ['room_id'], unique=False)
    op.add_column('user', sa.Column('private_key', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('public_key', sa.String(length=17), nullable=True))
    op.drop_column('user', 'vpn_ip')
    op.drop_column('user', 'vpn_mac')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vpn_mac', sa.VARCHAR(length=17), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('vpn_ip', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('user', 'public_key')
    op.drop_column('user', 'private_key')
    op.drop_index(op.f('ix_room_player_room_id'), table_name='room_player')
    op.drop_index(op.f('ix_room_player_player_username'), table_name='room_player')
    op.drop_table('room_player')
    op.drop_index(op.f('ix_chat_message_username'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_room_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_friendship_user_id'), table_name='friendship')
    op.drop_index(op.f('ix_friendship_friend_id'), table_name='friendship')
    op.drop_table('friendship')
    op.drop_table('network_config')
    # ### end Alembic commands ### 