"""Initial migration with fixed PK

Revision ID: 499fe5e465fc
Revises: b12afd853d8a
Create Date: 2025-05-29 01:24:10.576702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499fe5e465fc'
down_revision = 'b12afd853d8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 