"""fix_network_name_foreign_key

Revision ID: a80cee411fb5
Revises: fccc4fd229a6
Create Date: 2025-05-29 20:38:42.694326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80cee411fb5'
down_revision = 'fccc4fd229a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 