"""Initial migration with fixed PK

Revision ID: b12afd853d8a
Revises: 1fed805be004
Create Date: 2025-05-29 01:22:27.435241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12afd853d8a'
down_revision = '1fed805be004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_config', sa.Column('NETWORK_NAME', sa.String(length=100), nullable=True))
    op.drop_constraint('room_network_name_fkey', 'room', type_='foreignkey')
    op.drop_constraint('uq_network_config_network_name', 'network_config', type_='unique')
    op.create_unique_constraint('uq_network_config_network_name', 'network_config', ['NETWORK_NAME'])
    op.create_foreign_key('room_network_name_fkey', 'room', 'network_config', ['network_name'], ['NETWORK_NAME'], ondelete='CASCADE')
    op.drop_column('network_config', 'network_name')
    op.alter_column('user', 'private_key',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user', 'public_key',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'public_key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)
    op.alter_column('user', 'private_key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.drop_constraint('room_network_name_fkey', 'room', type_='foreignkey')
    op.drop_constraint('uq_network_config_network_name', 'network_config', type_='unique')
    op.create_unique_constraint('uq_network_config_network_name', 'network_config', ['network_name'])
    op.create_foreign_key('room_network_name_fkey', 'room', 'network_config', ['network_name'], ['network_name'], ondelete='CASCADE')
    op.add_column('network_config', sa.Column('network_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('network_config', 'NETWORK_NAME')
    # ### end Alembic commands ### 