"""initial structure

Revision ID: fe2ab63511d9
Revises: 
Create Date: 2025-05-12 01:15:59.081058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe2ab63511d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('user', sa.Column('ip_address', sa.String(length=15), nullable=True, unique=True))
    op.add_column('user', sa.Column('mac_address', sa.String(length=17), nullable=True, unique=True))
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_chat_message_id'), 'chat_message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('user', 'mac_address')
    op.drop_column('user', 'ip_address')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_id'), table_name='chat_message')
    op.alter_column('chat_message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ### 